###
# #%L
# MuleSoft Training - Anypoint Platform Development: Level 2
# %%
# Copyright (C) 2019 - 2023 MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
# %%
# The software in this package is published under the terms of the
# Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License,
# a copy of which has been included with this distribution in the LICENSE.txt file.
# #L%
###
flights:
  keystore:
    password:    "![2G6LpBPlXQ8orCV3UavFR9tHB5xyZT7x]"
    keyPassword: "![2G6LpBPlXQ8orCV3UavFR9tHB5xyZT7x]"

anypoint.mq:
  client_id:     "![LAJ0qxBpseLljzkAN4hChulbou5KaCjayVZQi6WV4vlgOS0fB/mHhw==]"
  client_secret: "![Q3BzRLe1LwP2S95V7MogqXjCt0AlNGza61FWHZt7Vl88kEDi35geSg==]"

tls.keystore:
  password:    "![ucbAFnF0v0FQKWPOKE5TCw==]"
  keyPassword: "![ucbAFnF0v0FQKWPOKE5TCw==]"
