###
# #%L
# MuleSoft Training - Anypoint Platform Development: Level 2
# %%
# Copyright (C) 2019 - 2023 MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
# %%
# The software in this package is published under the terms of the
# Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License,
# a copy of which has been included with this distribution in the LICENSE.txt file.
# #L%
###
# This environment (prod) is configured for deployment to a Mule runtime domain
api:
  id:       "15620142"               # autodiscovery API ID in API Manager in this environment
  callback:
   base:   "https://tngaa-flights-management-sapi-zkvtif.rajrd4-1.usa-e1.cloudhub.io"  

flights:
  responseTimeoutMillis:   "2000"
  alive: "https://tngaa-flights-management-zkvtif.u4ffml.usa-e1.cloudhub.io/alive"
  soap:
    base:  "https://tngaa-flights-management.prod-internalps.anyair.net"
  keystore:
    type:  "pkcs12"
    path:  "certs/clients-to-prod-internalps.p12"
    alias: "client"

vm:
  reconnectIntervalMillis: "1000"
  timeoutMillis:           "5000"
  maxRedeliveryCount:      "20"
  cancelNotif:
    q.size:   "1000"
    dlq.size: "10000"

anypoint.mq:
  url:                     "https://mq-us-east-1.anypoint.mulesoft.com/api/v1/organizations/a63e6d25-8aaf-4512-b36d-d91b90a55c4a/environments/12da2512-2379-4bcb-8c3f-b7e4a3d2e0c8"
  exchange:                "cancelled-flights-exchg"

tls.keystore:
  type:  "pkcs12"
  path:  "certs/${project.name}.p12" # replaced through Maven resource filtering
  alias: "server"
