###
# #%L
# MuleSoft Training - Anypoint Platform Development: Level 2
# %%
# Copyright (C) 2019 - 2023 MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
# %%
# The software in this package is published under the terms of the
# Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License,
# a copy of which has been included with this distribution in the LICENSE.txt file.
# #L%
###
api:
  id:       "15620145"               # autodiscovery API ID in API Manager in this environment

tls.keystore:
  type:  "pkcs12"
  path:  "certs/${project.name}.p12" # replaced through Maven resource filtering
  alias: "server"

db:
  host:          "a6e9b9e34024011eaac0706a9475cf8b-894813409.eu-west-2.elb.amazonaws.com"
  port:          "3038"
  # JDBC properties
  #sslmode:       "verify-ca"                                 # TODO: change to "verify-full" once real server is up
  #sslrootcert:   "${app.home}/certs/root-client.crt"         # ${app.home} provided by Mule runtime
  # Database details
  database:      "passenger_data"
  #url: "jdbc:postgresql://${db.host}:${db.port}/${db.database}?sslmode=${db.sslmode}&sslrootcert=${db.sslrootcert}"
  url: "jdbc:postgresql://${db.host}:${db.port}/${db.database}"
  timeOutMillis: "200"
