###
# #%L
# MuleSoft Training - Anypoint Platform Development: Level 2
# %%
# Copyright (C) 2019 - 2021 MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
# %%
# The software in this package is published under the terms of the
# Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License,
# a copy of which has been included with this distribution in the LICENSE.txt file.
# #L%
###
anypoint.mq:
  url: "https://mq-us-east-1.anypoint.mulesoft.com/api/v1/organizations/a63e6d25-8aaf-4512-b36d-d91b90a55c4a/environments/12da2512-2379-4bcb-8c3f-b7e4a3d2e0c8"
  destination: "cancelled-flights-mobile-queue"
  reconnectIntervalMillis: "1000"
