// Copyright (C) MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
//
// The software in this package is published under the terms of the
// Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License,
// a copy of which has been included with this distribution in the LICENSE.txt file.
= Case Study Solutions

Software solutions based on the AnyAirline case study:

* link:final[]: The complete, "final" solution to the case study, including all Mule apps and other artifacts.
* link:walkthroughs[]: Solutions and starters for the walkthroughs, based on aspects of the final solution.

== Build

. Create `etc/settings.xml` from link:etc/settings.xml.template[] adding the credentials missing in the latter.
. Get the two encryption keys for secure/encrypted properties files, one used in `final`, the other in `walkthroughs`.
. Run link:build.sh[], supplying the final and walkthroughs encryption keys on the command-line.

== Deploy

Deploy scripts are provided for the `final` case study solution: Start with link:final/deploy-the-entire-application-network.sh[] and instructions therein to deploy every Mule app of the final solution to all environments. This comprises a mix of deployments to CloudHub and an AWS Kubernetes cluster, as per the deployment architecture description in the Student Manual.
